### ISSUE TITLE
Add repo size badge

### ISSUE THREAD

**Issue by aha999** [bewue/Netvisix#1]
Since we need to copy a repo, it would be nice if the repo size was clearly visible from a badge in the top of the readme.

Badge: 
[![GitHub repo size](https://img.shields.io/github/repo-size/bewue/Netvisix)](https://github.com/bewue/Netvisix)

Code:
`[![GitHub repo size](https://img.shields.io/github/repo-size/bewue/Netvisix)](https://github.com/bewue/Netvisix)`

**Comment by bewue** [comment]
Added repo size badge to readme https://github.com/bewue/Netvisix/commit/f542ae9eb25f6368c7c83f1a01329a2f612545ff
